FROM python:3.11-slim

WORKDIR /opt/ironwall

ENV PYTHONUNBUFFERED=1
ENV SGX_MODE=SIM

COPY pyproject.toml README.md ./
COPY ironwall ./ironwall

RUN pip install --no-cache-dir -e .

EXPOSE 8765

CMD ["python", "-m", "ironwall.layer1_thinclient.server"]
